### PR TITLE
[DataTable] Make action menu more reliable

### LINKED ISSUE #51: ObjectsTable actions cleared on list() refresh
ObjectsTableRenderIssue

image

### PR DESCRIPTION
**Pull request by SferaDev**
* **Issue:** Closes #51

### CODE REVIEW

**Review by tokland — APPROVED** [review]
Very cool! It was specially annoying to lose the context menu when the snackbar disappeared.

**Comment by SferaDev** [comment]
This will conflict with https://github.com/EyeSeeTea/d2-ui-components/commit/508f23fb88cd0d1f4ac89a5e9687eaa6cb359559

**Comment by tokland** [comment]
> This will conflict with [508f23f](https://github.com/EyeSeeTea/d2-ui-components/commit/508f23fb88cd0d1f4ac89a5e9687eaa6cb359559)

I've tested merging this with feature/objects-table-improvements-10, I could not find the problem, what were you seeing?

**Comment by SferaDev** [comment]
> > This will conflict with [508f23f](https://github.com/EyeSeeTea/d2-ui-components/commit/508f23fb88cd0d1f4ac89a5e9687eaa6cb359559)
> 
> I've tested merging this with feature/objects-table-improvements-10, I could not find the problem, what were you seeing?

Weird, since we are changing getStateFromProps to be static and in #10 we are adding an instance call. Didn't try but noticed it wouldn't work.

I changed the method signatures as componentWillReceiveProps(newProps) was deprecated due to being unreliable. The static getDerivedStateFromProps is recommended as a replacement.

**Comment by SferaDev** [comment]
> > This will conflict with [508f23f](https://github.com/EyeSeeTea/d2-ui-components/commit/508f23fb88cd0d1f4ac89a5e9687eaa6cb359559)
> 
> I've tested merging this with feature/objects-table-improvements-10, I could not find the problem, what were you seeing?

Tested, and there're no problems at all! Works fine with #10

**Pull request merged**
