### PR TITLE
[Snackbar] Override styles to avoid empty space on multi-line messages

### LINKED ISSUE #45: Snackbar styles when message does not fit in single line
image

### PR DESCRIPTION
**Pull request by tokland**
Closes #45 

Single line:
image

Multi line:
image

### CODE REVIEW

**Review by SferaDev — COMMENTED** [review]
Since we are now reducing the width of the message, the margins don't look aligned properly.

Proposal:

```
    iconVariant: {
        opacity: 0.9,
        marginRight: theme.spacing.unit * 4, // Or anything between 30px and 38px
    },
```

Before: 

image

image


After: 

image

image

**Comment by tokland** [comment]
@SferaDev Looks good to me, go ahead with the push.

**Review by SferaDev — APPROVED** [review]

**Comment by adrianq** [comment]
@tokland @SferaDev Thanks for this! I am merging this but something very minor and not related with this I have noticed:
image

**Comment by tokland** [comment]
Yep, that's something that came up in a team meeting, let me check with @SferaDev how to fix it.

**Comment by tokland** [comment]
Issue opened: https://github.com/EyeSeeTea/vaccination-app/issues/286

**Comment by adrianq** [comment]
Thanks!

**Pull request merged**
